version: 0.2.5
slug: openthread_border_router
name: OpenThread Border Router
description: OpenThread Border Router add-on
url: https://github.com/home-assistant/addons-development/tree/master/openthread_border_router
arch:
  - armv7
  - aarch64
  - amd64
hassio_api: true
# IPC is only used within the Add-on
host_ipc: false
host_network: true
privileged:
  - IPC_LOCK
  - NET_ADMIN
image: homeassistant/{arch}-addon-otbr
init: false
options:
  device: null
  baudrate: 115200
  flow_control: false
  otbr_debug: false
  firewall: true
schema:
  device: device(subsystem=tty)
  baudrate: list(57600|115200|230400|460800|921600)
  flow_control: bool
  otbr_debug: bool
  firewall: bool
stage: experimental
startup: services
ingress: true
ingress_port: 8080
panel_title: OpenThread
panel_icon: mdi:view-grid-plus-outline
panel_admin: true
