version: 0.1.0
slug: silabs_multiprotocol
name: Silicon Labs Multiprotocol
description: Zigbee and OpenThread multiprotocol add-on
url: https://github.com/home-assistant/addons-development/tree/master/silabs-multiprotocol
arch:
  - armv7
# Currently zigbeed crashes with *** stack smashing detected ***
#  - aarch64
hassio_api: true
privileged:
  - IPC_LOCK
image: ghcr.io/home-assistant/{arch}-addon-silabs-multiprotocol
init: false
options:
  device: null
  cpcd_trace: false
  socat_trace: false
ports:
  9999/tcp: null
schema:
  device: device(subsystem=tty)
  cpcd_trace: bool
  socat_trace: bool
stage: experimental
startup: services
