version: 0.2.0
slug: silabs_multiprotocol
name: Silicon Labs Multiprotocol
description: Zigbee and OpenThread multiprotocol add-on
url: https://github.com/home-assistant/addons-development/tree/master/silabs-multiprotocol
arch:
  - armv7
  - aarch64
hassio_api: true
# IPC is only used within the Add-on
host_ipc: false
privileged:
  - IPC_LOCK
image: homeassistant/{arch}-addon-silabs-multiprotocol
init: false
options:
  device: null
  cpcd_trace: false
  socat_trace: false
ports:
  9999/tcp: null
ports_description:
  9999/tcp: EmberZNet EZSP/ASH port
schema:
  device: device(subsystem=tty)
  cpcd_trace: bool
  socat_trace: bool
stage: experimental
startup: services
