name: Remote ptvsd debugger
version: 1.2.0
slug: remote_debug
description: Remote Debug proxy for Supervisor/ptvsd
url: https://developers.home-assistant.io/docs/supervisor/debugging
arch:
- aarch64
- amd64
startup: once
advanced: true
stage: experimental
boot: manual
ports:
  33333/tcp: 33333
options: {}
schema: false
image: homeassistant/{arch}-addon-dev-remote_debug
init: false
