name: Remote API proxy
version: 1.3.0
slug: remote_api
description: Remote API proxy for Home Assistant
url: https://developers.home-assistant.io/docs/supervisor/development/#supervisor-api-access
arch:
- aarch64
- amd64
startup: once
stage: experimental
boot: manual
hassio_api: true
hassio_role: admin
ports:
  80/tcp: 80
options: {}
schema: false
image: homeassistant/{arch}-addon-dev-remote_api
init: false
